### ISSUE TITLE
about  detectron2    version   error ？  I use source code to install detectron2-0.6（https://github.com/facebookresearch/detectron2/releases/tag/v0.6）

### ISSUE THREAD

**Issue by zhanghongyong123456** [hustvl/ViTMatte#6]
v0.6  version     batch_norm   doesn't have the 'LN' method? 
 
![image](https://github.com/hustvl/ViTMatte/assets/48466610/2d951e69-518c-4872-ba10-88b21041bf7e)

I compared the latest version of the code with version 0.6 and found that this method was indeed missing

![image](https://github.com/hustvl/ViTMatte/assets/48466610/b9fc4a71-c452-4647-8559-a7d87a665e88)
![image](https://github.com/hustvl/ViTMatte/assets/48466610/59006181-ab91-42ba-a6bd-1705148dc8c5)

**Comment by JingfengYao** [comment]
Thanks for your observation. 
I've checked the d2 version in my environment and it is shown as follows:
![image](https://github.com/hustvl/ViTMatte/assets/88607821/5e860947-7089-49fc-b37f-f4f07ed56261)
But I just built d2 from the **latest source code** instead of the released pre-built v0.6 one. So I checked the source code in d2 and found that its version is fixed at 0.6 since two years ago, which caused the misunderstanding. 
<img src="https://github.com/hustvl/ViTMatte/assets/88607821/34e1e46b-4c00-42f4-b9ce-960aa9aaf22d" width="400" height="300" alt="image">
For ViTMatte, you could build d2 from the **latest source codes**. If it still does not work, please let me know and I'll try to help.

**Comment by zhanghongyong123456** [comment]
> Thanks for your observation. I've checked the d2 version in my environment and it is shown as follows: ![image](https://user-images.githubusercontent.com/88607821/247026711-5e860947-7089-49fc-b37f-f4f07ed56261.png) But I just built d2 from the **latest source code** instead of the released pre-built v0.6 one. So I checked the source code in d2 and found that its version is fixed at 0.6 since two years ago, which caused the misunderstanding. <img alt="image" width="400" height="300" src="https://user-images.githubusercontent.com/88607821/247028425-34e1e46b-4c00-42f4-b9ce-960aa9aaf22d.png"> For ViTMatte, you could build d2 from the **latest source codes**. If it still does not work, please let me know and I'll try to help.

it is   OK ,  use   latest(main) code,  I recommend stating on the project home page that using the latest code (especially for windows users, source code compilation is required)

**Comment by JingfengYao** [comment]
@zhanghongyong123456 
We have updated it. Thanks for your suggestion. 😄

**Comment by zhanghongyong123456** [comment]
> @zhanghongyong123456 We have updated it. Thanks for your suggestion. 😄

Thanks again for a great project
